before_script:
  - docker info

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - docker
  script:
    - echo "Build 'Simple Blog'"
    - if [[ $( docker ps -aq | wc -l ) -gt 0 ]]; then docker rm -f $( docker ps -aq ); else echo "no containers to clean"; fi
    - sleep 1
    - if [[ $( docker images -q | wc -l ) -gt 0 ]]; then docker image rm -f $( docker images -q ); else echo "no images to clean"; fi
    - sleep 1
    - docker build --rm -t keyteo/simpleblog .
  only:
    - master
    - tags

test:
  stage: test
  tags:
    - docker
  script: 
    - echo "Test project"
    - docker run --rm -t -v $( pwd )/tests:/app/tests keyteo/simpleblog sh -c ". bin/activate && pip install -e . && coverage run -m pytest && coverage report"
  only:
    - master
    - tags

deploy_staging:
  stage: deploy
  tags:
    - docker
  script:
    - echo "Deploy to staging server"
    - if [[ $( docker ps -aq | wc -l ) -gt 0 ]]; then docker rm -f $( docker ps -aq ); else echo "no containers to clean"; fi
    - sleep 3
    - docker run -p 8071:8071 -d keyteo/simpleblog sh -c ". bin/activate && pip install -e . && flask init-db && waitress-serve --url-scheme=http --listen=0.0.0.0:8071 --no-ipv6 --call simpleblog:create_app"
  environment:
    name: staging
    url: http://http://keyteo-gitlab.westeurope.cloudapp.azure.com:8071
  only:
    - master
    - tags
  when: on_success
